consumes:
- application/json
info:
  description: REST interface for lab items reserved by a person until a date
  title: labreserved
  version: 0.0.1
produces:
- application/json
schemes:
- https
- http
swagger: "2.0"

paths:
  /items:
    get:
      responses:
        200:
          description: list all items in the lab
          schema:
            type: object
            $ref: "#/definitions/items"
  /item:
    post:
      description: add a single item to the lab list
      parameters:
        - name: additem
          description: representation of the item to add
          in: body
          required: true
          schema:
            $ref: "#/definitions/item"
      responses:
        200:
          description: Accepted
          schema:
            type: object
            $ref: "#/definitions/item"
        400:
          description: Error
          schema:
            type: string
definitions:
  items:
    description: map of items
    type: object
    additionalProperties:
      $ref: "#/definitions/item"
  item:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      name:
        type: string
        minLength: 1
        maxLength: 512
        description: name of the thing in the lab reserved
      description:
        type: string
        minLength: 1
        maxLength: 2048
      reservedUntil:
        type: string
        format: date-time
        description: date/time this reservation will expire
      reservedBy:
        $ref: "#/definitions/user"
  users:
    description: map of users
    type: object
    additionalProperties:
      $ref: "#/definitions/user"
  user:
    type: object
    required:
      - name
      - email
    properties:
      id:
        type: integer
        format: int64
        readOnly: true
      email:
        type: string
        format: email
        description: user contact email
      name:
        type: string
        minLength: 1
        maxLength: 512
        description: reservation user's name

